export const GET_PARAM_BY_KEY = "GET_PARAM_BY_KEY";
export const GET_ALL_PASS = "GET_ALL_PASS";
export const SET_LOADING = "SET_LOADING";
export const GET_CONFIG_PASS_ACTIVE = "GET_CONFIG_PASS_ACTIVE";





export const PARTNER_CONFIG = "PARTNER_CONFIG";
export const ELITE_CONFIG = "ELITE_CONFIG";
export const PREMIUM_CONFIG = "PREMIUM_CONFIG";
export const CONFIG_PASS_PARTNER = "CONFIG_PASS_PARTNER";
export const CONFIG_PASS_ELITE = "CONFIG_PASS_ELITE";
export const CONFIG_PASS_PREMIUM = "CONFIG_PASS_PREMIUM";
