export const CREATE_USER = "CREATE_USER";
export const GET_USER_BY_WALLET = "GET_USER_BY_WALLET";
export const UPDATE_NEW_PASS = "UPDATE_NEW_PASS";
export const GET_REFERRAL_MOVEMENT = "GET_REFERRAL_MOVEMENT";
export const SET_REFERRAL_BY_LINK = "SET_REFERRAL_BY_LINK";